name: OnPush

on:
  push:

jobs:
  test_workflow:
    name: OnPush
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Git config
        run: |
          git config --global user.email "si.ma@fresha.com"
          git config --global user.name "si.ma"

      - name: Publish to another repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.TOKENS_RELEASE_IOS_REPO_SSH }}
        with:
          source-directory: 'design_tokens_ios'
          destination-github-username: ${{ env.GITHUB_ACTOR }}
          destination-repository-name: 'sima-fresha/push-test'
          target-branch: main