name: Test

on:
  push:
    tags:
    - '*'

jobs:
  test_workflow:
    name: Test2
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create package
        working-directory: ./design_tokens_ios
        run: |
          swift package generate-xcodeproj
          xcodebuild archive \
            -project design_tokens_ios.xcodeproj \
            -scheme design_tokens_ios-Package \
            -destination "generic/platform=iOS Simulator" \
            -archivePath "archives/design_tokens_ios_simulator.xcarchive" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          xcodebuild archive \
            -project design_tokens_ios.xcodeproj \
            -scheme design_tokens_ios-Package \
            -destination "generic/platform=iOS" \
            -archivePath "archives/design_tokens_ios.xcarchive" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          xcodebuild -create-xcframework \
             -framework archives/design_tokens_ios_simulator.xcarchive/Products/Library/Frameworks/design_tokens_ios.framework \
             -framework archives/design_tokens_ios.xcarchive/Products/Library/Frameworks/design_tokens_ios.framework \
             -output output/design_tokens_ios.xcframework

      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./design_tokens_ios/design_tokens_ios.xcframework