name: Build artifacts

on:
  workflow_call:

jobs:
  build_artifacts:
    name: Build artifacts
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Swift package
        run: swift build --package-path ../../design_tokens_ios
        
      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2
