name: Test

on:
  push:
    tags:
    - '*'

jobs:
  test_workflow:
    name: Test2
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup mint
        uses: fabasoad/setup-mint-action@main

      - name: Install tooling
        run: mint install unsignedapps/swift-create-xcframework

      - name: Create package
        run: mint run swift design_tokens_ios --platform ios --package-path ./design_tokens_ios --zip-version 1.0

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./design_tokens_ios-1.0.zip