name: Test

on:
  push:

jobs:
  test_workflow:
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
  build_artifacts:
    needs: release
    uses: sima-refresha/workflow_test/.github/workflows/test-build-artifacts.yml@main
